apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: europe-west1-docker.pkg.dev/d-com-437216/cluster-repo/frontend:latest
        ports:
        - containerPort: 80  # The container listens on port 80

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80         # External port (how the service is exposed)
      targetPort: 80     # Internal port (the port your app runs on inside the container)
  type: ClusterIP        # Use LoadBalancer or NodePort if external access is needed
